
# ============================================================================
# 【ENG】 x-do Batch Configuration File
# 【POL】 Plik konfiguracji wsadowej x-do
# ============================================================================

[[job]]
id = "default_job"
name = "snapshot-project"
description = "【ENG】 Standard Rust project snapshot / 【POL】 Standardowy zrzut projektu Rust"
quiet_work = true

[job.scan]
work_path = "."
patterns = [
    "./{.rustfmt,Cargo,rust-toolchain,Makefile}.toml&/",
    "./**/*.rs&/",
    "!./target/**",
    "!./temp/**",
    "!./.git/**",
    "./.{gitattributes,gitignore}",
    "./.github/workflows/*.yml&/",
    "./.vscode/settings.json&/",
    "./{API,ARCHITECTURE,AUTHORS,CHANGELOG,README,ROADMAP,TODO}.md"
]
ignore_case = false

[job.spec]
mode = "m"
hide_stats = false
hide_promo = false

[job.spec.trimming]
# show_page = 1
# page_size = 20

[job.table_sotc]
sort_by = "kind"
sort_order = "asc"
reverse = false
structure = "tree"
columns = ["date", "time", "size", "tree", "icon", "number", "path"]
trim_page = 1
more_icons = false

[job.export]
save_sotc_at = "./target/.cargo-plot/File"
title_sotc = "Rust Project Snapshot [Structure of the content]"
save_cots_at = "./target/.cargo-plot/Docs"
title_cots = "Rust Project Snapshot [Content of the structure]"
