# .cargo/config.toml

# Wymuszenie statycznego linkowania bibliotek C (CRT) dla Windows.
# Dzięki temu plik .exe będzie działał na czystym Windows 7/8/10/11
# bez konieczności instalowania "Visual C++ Redistributable".

# Konfiguracja dla standardowych systemów 64-bitowych (Większość dzisiejszych PC)
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# Konfiguracja dla starych systemów 32-bitowych (Stare laptopy, Windows XP/7 32-bit)
[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]